// File: apps/api/Application/DTOs/Order/CreateOrderDto.cs
// Input DTO for creating order from cart

using api.Domain.Enums;

namespace api.Application.DTOs.Order;

public class CreateOrderDto
{
    // Payment method chosen
    public PaymentMethod PaymentMethod { get; set; }

    // Optional coupon
    public string? CouponCode { get; set; }

    // Idempotency key (generated by frontend to prevent duplicate orders)
    public string? IdempotencyKey { get; set; }

    // Customer note (delivery instructions etc.)
    public string? CustomerNotes { get; set; }

    // ==========================================
    // SHIPPING ADDRESS
    // ==========================================

    public string FullName { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
    public string AddressLine1 { get; set; } = string.Empty;
    public string? AddressLine2 { get; set; }
    public string? Landmark { get; set; }
    public string City { get; set; } = string.Empty;
    public string State { get; set; } = string.Empty;
    public string Pincode { get; set; } = string.Empty;
    public string Country { get; set; } = "India";
}